### ISSUE TITLE
gestion des tabindex -1 quand modale ouverte

### ISSUE THREAD

**Issue by goetsu** [nico3333fr/jquery-accessible-modal-window-aria#10]
hello, sur ton script modale je viens de me rendre compte que tu n'appliquais pas de tabindex -1 aux liens, element de formulaire etc en arrière plan du coup si je remet le focus sur la barre d'adresse puis retabule je repasse en dessous de la modale.

Un correctif de base pourrait être de mettre la modale en 1er dans le code source mais cela poserait toujours souci si l'utilisateur fait shift tab au lieu de tab

Enfin si tu implémente gestion des tabindex -1 : 
- je recommande de le rendre désactivable car c'est généralement assez gourmand sur les grosses pages. 
- il faut appliquer le tabindex -1 à tout ce qui est tabulable donc les liens, les buttons, les input, les select, les textarea, les éléments avec un tabindex >=0 (attention pour ceux là il faudra à la fermeture remettre leur valeur tel qu'elle était)

**Comment by nico3333fr** [comment]
Yop,

je suis en train d'y réfléchir, et je viens d'avoir une idée : pourquoi ne pas ajouter un listener qui détecte si le focus est ailleurs que dans la modale, et qui le remet dedans ? (c'est p-e plus simple)

Qu'en penses-tu mon cher @goetsu ? :)

**Comment by goetsu** [comment]
à tester oui

**Comment by nico3333fr** [comment]
Yop @goetsu je crois que c'est bon, tu peux tester sur http://a11y.nicolas-hoffmann.net/modal/ ?

**Comment by goetsu** [comment]
dans ta démo y a un bug avec la modale 'it's accessible' dans celle là le focus reste bloqué quand on tab après le 1er lien dans la modale et quand on shift tab il sort de la modale

**Comment by nico3333fr** [comment]
Diantre, bien vu, j'essaie de fixer...

**Comment by nico3333fr** [comment]
Ok, j'avais merdé ma fonction, j'ai fait autrement, ça devrait être bon cette fois. Un ch'ti test ? :)

**Comment by goetsu** [comment]
ok y a plus le bug et le bug d'origine est quasi corrigé, quasi car j'ai toujours le 1er lien dans la page sous la modale qui reçoit le focus si je remet le focus sur la barre d'adresse puis retabule quand modale ouverte

**Comment by nico3333fr** [comment]
J'ai updaté le script, avec .on ( "keyup, 
ça a l'air d'être bon !

**Comment by goetsu** [comment]
oui c'est bon maintenant

**Comment by nico3333fr** [comment]
cool, je shippe dès que possible, encore merci :)
Ce qui va résoudre aussi le cas de la page qui utilise une modale automatiquement.
