### ISSUE TITLE
Uncaught ReferenceError: $close is not defined

### ISSUE THREAD

**Issue by pepemiyashiro** [nico3333fr/jquery-accessible-modal-window-aria#16]
Hello,

I found this error log.
And this is related to the variables declaration on line: 184

```
var $this = $(this),
      $js_modal = $('#js-modal'),
      focusedItem = $( document.activeElement ),
      in_jsmodal = focusedItem.parents('#js-modal').length ? true : false;
     $close = $('#js-modal-close');
```

I found that the in_jsmodal assigment end in a semicolon, and it should be a comma.

Shold be like this:
```
var $this = $(this),
      $js_modal = $('#js-modal'),
      focusedItem = $( document.activeElement ),
      in_jsmodal = focusedItem.parents('#js-modal').length ? true : false,
     $close = $('#js-modal-close');
```

Hope it helps.

**Comment by nico3333fr** [comment]
Hi @pepemiyashiro 

thanks a lot for pointing it out, I've fixed it.

Kind regards,
Nicolas

**Comment by pepemiyashiro** [comment]
Hi @nico3333fr You are welcome. And thanks for the nice modal plugin you have done.

Thanks you
