### ISSUE TITLE
Untranslatable text in background modal

### ISSUE THREAD

**Issue by juliemoynat** [nico3333fr/jquery-accessible-modal-window-aria#19]
Hi,

The text in the background modal in not translatable:
`<span id="js-modal-overlay" class="simple-modal-overlay" title="Fermer" data-background-click="enabled"><span class="invisible">Close modal</span></span>`

Could it be in a "data" attribute?

**Comment by nico3333fr** [comment]
Hi,

you're right, it was missing, I've fixed it in last commit. 

I've used the ```data-modal-close-text``` value.

Thanks for pointing it out 👍
