### ISSUE TITLE
attribute to focus something after opening

### ISSUE THREAD

**Issue by jpyrat** [nico3333fr/jquery-accessible-modal-window-aria#20]
Hi,

Could you had the possibility to focus a form field ?
With something like : 
data-modal-focus-id

Thx !

**Comment by nico3333fr** [comment]
Hi,

why not, a good idea :)

**Comment by jpyrat** [comment]
You can look here for the need for that : http://stpeter-gallicantu.org point g2w point fr/-Rubriques-.html

**Comment by nico3333fr** [comment]
Here we go, the option is added, and the documentation is updated: https://a11y.nicolas-hoffmann.net/modal/

Thanks for the suggestion ;)

**Comment by jpyrat** [comment]
Thx !
