### ISSUE TITLE
keep link action with class="js-modal-close"

### ISSUE THREAD

**Issue by jpyrat** [nico3333fr/jquery-accessible-modal-window-aria#28]
Salut Nicolas,

J'ai voulu mettre class="js-modal-close" sur un lien d'une modale qui pointait vers une ancre de la page en cours.
Mais dans ce cas, le close se produit sans que l'action du lien ne soit faite.

Et sans le close, le scroll se produit dans la page sous la boite de dialog, mais quand je clique sur le bouton close, le focus est remis sur le bouton qui avait ouvert la boite.

C'est quelque chose que tu peux voir en allant sur https://formation.soyezcreateurs.net/Raccourcis-Typographiques-de-SPIP-mode-d-emploi.html et en cliquant sur l'icone d'agenda en haut à droite. Puis en cliquant sur l'item en dessous du tableau (Raccourcis Typographiques de SPIP, mode d’emploi : Formation Le mercredi 1 décembre 2021 à 09:30). Là, tu vois le scroll en dessous.

Est-ce que c'est clair ?
Est-ce que ma demande est légitime ?

**Comment by jpyrat** [comment]
À première vue, il suffirait de retirer 
https://github.com/nico3333fr/jquery-accessible-modal-window-aria/blob/master/jquery-accessible-modal-window-aria.js#L163

Ce que je viens de tester avec succès.

**Comment by nico3333fr** [comment]
Ah oui, effectivement. Je reconnais que le event.preventDefault n'est pas forcément nécessaire pour le coup, et même contreproductif.

Tu veux faire une PR ou je fixe ?

**Comment by jpyrat** [comment]
PR faite, merci ;-)

**Comment by nico3333fr** [comment]
Super, j'ai mergé :)
