### ISSUE TITLE
Pas de scroll

### ISSUE THREAD

**Issue by davidpollet** [nico3333fr/jquery-accessible-modal-window-aria#4]
Salut Nico :)
Il est impossible de scroller la fenêtre modale si elle se trouve trop près de la fin du contenu. 
Je t'ai fais un codepen à partir de ta demo : http://codepen.io/anon/pen/azeELN

T'as juste qu'à baisser exagerement la hauteur du compartiment en dessous des codes html/css/js puis cliquer sur le button "another modal" pour constater. ;)

++ ;)

**Comment by nico3333fr** [comment]
Salut,

oui, c'est un problème que j'ai eu sur mobile, je l'avais résolu en la positionnant en haut de la page, mais c'est du bricolage. (android m'avait un eu fait ch..., j'avais dû bidouiller) 

Faudrait soit autoriser le scroll en interne, soit tricher un peu avec des vh, mais pas de compatibilité pour les vieux navigateurs... :-\

**Comment by davidpollet** [comment]
Si ça peut t'aider et que tu souhaites ajouter le scroll, je connais un plugin jquery qui gère le gère très bien.
http://lab.veno.it/venobox/

Je dois partir sur une autre piste parce que je voulais me servir de ton plugin pour afficher une fenêtre modale du même genre que les présentations Behance. Je suis obligé de laisser dans le bas de ma page dans mon cas et le "problème" se produit aussi sur desktop.

Merci pour la réponse rapide. ^^

**Comment by nico3333fr** [comment]
N'oublie pas que tu peux en modifier le positionnement dans ton cas, au lieu de top:0 tu peux mettre bottom 0 ;)

**Comment by davidpollet** [comment]
Je ne comprends pas. Où tu mettrais bottom:0 ?

**Comment by nico3333fr** [comment]
Dans les styles pour positionner la modale. :)

**Comment by davidpollet** [comment]
Marche pas ou je suis à côté de la plaque ('Fait trop chaud dans le nord. ^^) Par contre, si tu changes en absolute au lieu de fixed sur la modale, ça a l'air de scroller (marche sur FF) sauf que tu scrolles aussi ce qu'il y a en dessous de la modale.

**Comment by nico3333fr** [comment]
Tu aurais un exemple où je peux regarder ce qui cloche ?

**Comment by davidpollet** [comment]
Salut Nico,
http://codepen.io/anon/pen/azeELN

A nouveau, il te suffit de choper la barre horizontale qui sépare le code du rendu et de la pousser vers le bas.
Avec .modal en position absolute et en ne mettant pas de valeur bottom, ça fonctionne mais tu scrolles aussi ce qu'il y a en dessous.

Peut-être qu'il faudrait extraire tout ce qui n'appartient pas à la modale et le mettre dans un conteneur en position fixe pour éviter que ça bouge par exemple. Excuses-moi, je ne sais pas traduire ça en JS.

Je déménage demain donc je vais perdre ma raison de vivre pendant quelques jours (^^), sauf si je choppe un accès wifi d'un voisin. J'essayerai de surveiller l'évolution au cas où tu as besoin de moi.
Bonne soirée / journée.
++ :)

**Comment by davidpollet** [comment]
Bon bah j'ai pas déménagé.
Je suis relativement dispo si besoin. J'espère avoir répondu à ta demande. J'ai dû opter pour venobox pour mon portfolio que je lancerai peut-être éventuellement -on ne sait jamais - un 30 fevrier si j'arrive à être satisfait.

De toute façon, je t'ai à l'oeil. :p J'utilise quasi tout tes pluggins. <3
++ ;)

**Comment by nico3333fr** [comment]
Je viens de modifier le script et le site de démo et je crois que ça résout ton problème. :)

**Comment by davidpollet** [comment]
Salut Nico,
Content de lire ça. Joyeuses fêtes ! ^^
